CREATE TABLE FILE_INFO
(
    ID INTEGER PRIMARY KEY,
    NAME TEXT UNIQUE NOT NULL,
    WATCH_DATE TEXT NOT NULL
);

CREATE TABLE VARIABLE
(
    ID INTEGER PRIMARY KEY,
    NAME TEXT UNIQUE NOT NULL,
    VALUE TEXT NOT NULL
);

INSERT INTO VARIABLE (NAME, VALUE) VALUES ('PATH', 'D:\test');
INSERT INTO VARIABLE (NAME, VALUE) VALUES ('PATTERN', '\{0\}');
INSERT INTO VARIABLE (NAME, VALUE) VALUES ('WATCHED_DATE', '600000');
INSERT INTO VARIABLE (NAME, VALUE) VALUES ('SCRIPT', 'test.bat');