CREATE TABLE VARIABLE
(
    ID INTEGER PRIMARY KEY,
    NAME TEXT UNIQUE NOT NULL,
    VALUE TEXT NOT NULL
);

CREATE TABLE FILE_INFO
(
    ID INTEGER PRIMARY KEY,
    NAME TEXT UNIQUE NOT NULL,
    WATCH_DATE TEXT NOT NULL
);